services:
  - type: web
    name: auracut-ai-background-remover
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MAX_UPLOAD_MB
        value: "10"
      - key: CLIPDROP_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DELETE_TOKEN_SECRET
        generateValue: true
